---
- name: Configure systemd-journald parameters
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-journald
